### ISSUE TITLE
AutoSharedPreferenceConfig找不到

### ISSUE THREAD

**Issue by 772865705** [linkaipeng/AutoSharedPreference#2]
App初始化的时候 编译器找不到这个类 编译不通过
AutoSharedPreferenceConfig

**Comment by 772865705** [comment]
@AutoSharedPreferences
public class SPDefault {

    @AutoGenerateField(defaultStringValue = "zhaoyue1")
    private String name;

}

实体类里面的注解没问题 编译可以通过

**Comment by linkaipeng** [comment]
这个类也是自动生成的，找不到的话。估计是编译没有成功；编译成功的话，在 build-generated-source 里面是可以看到生成的类的
